name: "Exercice 2"
run-name: ${{github.actor}} Exercice 2
on: 
  push:

jobs:
  exercice1: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - uses: stefanoeb/eslint-action@1.0.2
        run: eslint . --ext .js,.jsx,.ts,.tsx