name: "Exercice 2"
run-name: ${{github.actor}} Exercice 2
on: 
  push:

jobs:
  exercice1: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/